### ISSUE TITLE
Talk 02.12.2022

### ISSUE THREAD

**Issue by bujowskis** [bujowskis/mk-convection-selection-22-23#33]
### TODO
- [x] resolve namespace package - `__init__.py` (packaging the modules, using outside of source directory, the same way as in `framsfiles`) -> `convection_selection` subpackage outside, not duplicating code, etc.
- [x] refactoring into pythonic way of writing code
  - CamelCaseClasses, methods_with_underscore, vars_with_underscore, self_explanatory_variables
  -  `BUT` may need to stick to it (standards, previous code, faster)
- [x] numerical benchmarks
  - are we still using numerical benchmarks using Framsticks engine? / our computational engine?
  - `numerical_base` folder? (concrete implementations of `base/abc`, the same way `frams_base`
  - example of running numerical benchmark (same as `experiment_frams.py`
- [x] TDD, Unit Tests 
  - ofc, tests for CS
  - "what if we need to change/optimize sth else?" (vectors instead of for loops in individual.py "
  - why no tests in evolalg, the same way in `framsfiles`
  - approach: take for granted the code we rely on works, ask for/create tests if we need to change them
- [x] failed parameter - dissim method -2
```
Experiment with params:{'opt': 'velocity', 'max_numparts': None, 'max_numjoints': 20, 'max_numneurons': 20, 'max_numconnections': None, 'max_numgenochars': 20, 'hof_size': 0, 'normalize': 'none', 'dissim': -2, 'fit': 'niching', 'genformat': '1', 'popsize': 8, 'archive': 8, 'initialgenotype': None, 'pmut': 0.7, 'pxov': 0.2, 'tournament': 5} failied with the stack:Don't know what to do with dissimilarity method = -2
```
- [x] failed with the stack:kth(=30) out of bounds (7)
```
Experiment with params:{'opt': 'vertpos', 'max_numparts': None, 'max_numjoints': 20, 'max_numneurons': 20, 'max_numconnections': None, 'max_numgenochars': 20, 'hof_size': 10, 'normalize': 'sum', 'dissim': 2, 'fit': 'nslc', 'genformat': '1', 'popsize': 8, 'archive': 8, 'initialgenotype': None, 'pmut': 0.7, 'pxov': 0.2, 'tournament': 5} failied with the stack:kth(=30) out of bounds (7)
```
- [x] moving framspy to git?
  - easier collaboration (centralized, pull-requests, etc.)
  - more approachable and popular
  - avoid duplicate - we only get acknowledged for what we've actually done
- [x] don't make people move files manually (deap .dll)
  - _it may also contain dev features, if you know what you're doing_?
- [x] (code questions)
